CREATE TABLE IF NOT EXISTS CUSTOMERS_INFO (
    CUSTOMER_ID BIGINT,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    CONTACT VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    BIRTH_DATE VARCHAR(255) NOT NULL
    )